# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_int <- function(B, E, S) {
    .Call('_rcov_sample_int', PACKAGE = 'rcov', B, E, S)
}

rcpp_block_cv <- function(x, S, h, tau_vec, M_est) {
    .Call('_rcov_rcpp_block_cv', PACKAGE = 'rcov', x, S, h, tau_vec, M_est)
}

rcpp_huber_mean <- function(x, tau) {
    .Call('_rcov_rcpp_huber_mean', PACKAGE = 'rcov', x, tau)
}

rcpp_spec_block_cv <- function(X, S, h, lag, tau_vec) {
    .Call('_rcov_rcpp_spec_block_cv', PACKAGE = 'rcov', X, S, h, lag, tau_vec)
}

rcpp_spec_trunc_autocov <- function(X, l, tau) {
    .Call('_rcov_rcpp_spec_trunc_autocov', PACKAGE = 'rcov', X, l, tau)
}

rcpp_trunc_mean <- function(x, tau) {
    .Call('_rcov_rcpp_trunc_mean', PACKAGE = 'rcov', x, tau)
}

